* meow-cjk

Han word segmentation support for [[https://github.com/meow-edit/meow][Meow]] modal editing.

** Features

- Han word selection and movement for Meow word commands
- EMT backend backed by [[https://github.com/messense/jieba-rs][jieba-rs]]
- Lazy module loading so startup is not blocked when the EMT module is missing
- macOS, Linux, and Windows support through EMT's dynamic module

** Requirements

- Emacs 27.1+
- [[https://github.com/meow-edit/meow][Meow]] 1.5.0+
- [[https://github.com/LuciusChen/emt][EMT]] 0.1.2+

** Installation

*** straight.el

#+begin_src elisp
(use-package emt
  :straight (:host github :repo "LuciusChen/emt"))

(use-package meow-cjk
  :straight (:host github :repo "LuciusChen/meow-cjk")
  :after meow
  :config
  (meow-cjk-mode 1))
#+end_src

*** package.el

#+begin_src elisp
(package-vc-install "https://github.com/LuciusChen/emt")
(package-vc-install "https://github.com/LuciusChen/meow-cjk")

(require 'meow-cjk)
(meow-cjk-mode 1)
#+end_src

** Usage

Enable =meow-cjk-mode= to make these Meow word commands use EMT's Han
segmentation:

| User command     | Advised internal  | Description                                  |
|------------------+-------------------+----------------------------------------------|
| =meow-mark-word= | =meow-mark-thing= | Mark the Han word at point                   |
| =meow-next-word= | =meow-next-thing= | Select to the end of the next Han word       |
| =meow-back-word= | =meow-next-thing= | Select to the beginning of the previous word |

** EMT Module

If the EMT dynamic module is missing, startup and =meow-cjk-mode= activation do
not fail.  The first Han-aware command that needs segmentation will ask EMT to
load the module.  Install the pre-built module with:

#+begin_src elisp
M-x emt-download-module
#+end_src

** Limitations

This package is Han-focused because EMT uses jieba-rs.  It does not segment
Japanese kana or Korean Hangul.

** License

GPL-3.0-or-later

** Related

- [[https://github.com/meow-edit/meow][Meow]] - Modal editing
- [[https://github.com/LuciusChen/emt][EMT]] - Han word boundaries via jieba-rs
